# Data restructuring
## This is meant as a temporary workflow to restructure
## This will changed when a stable version is produced which is:
### These requirements are:
### - Create a matrix collection of SNP data
### - Create a new collection variant sample data

In [90]:
# imports appropiate packages
import pandas as pd
import numpy as np
import pymongo

In [91]:
db = pymongo.MongoClient('localhost',27017).sarscov2_standalone

In [92]:
samples = [x for x in db.sample.find()]
variants = [x for x in db.variant.find()]
depth = [x for x in db.depth.find()]

In [93]:
df = pd.DataFrame()
col_name = ''
col = []
index = []
for i, ele in enumerate(depth):
    if i == 0:
        col_name = ele['sample_id']
    if ele['sample_id'] != col_name:
        df[col_name] = col
        col_name = ele['sample_id']
        col = []
        index = []
    temp = [ele['A'], ele['T'], ele['C'], ele['G']]
    col.extend([x/max(temp)  if max(temp) != 0 else np.nan for x in temp] )
    index.extend([f'{ele["pos"]}_A', f'{ele["pos"]}_T', f'{ele["pos"]}_C', f'{ele["pos"]}_G'])
    
df.index = index

In [94]:
df.transpose().fillna(df.transpose().mean()).transpose()

,sc2-1001,sc2-1002,sc2-1003,sc2-1004,sc2-1005,sc2-1006,sc2-1007,sc2-1008,sc2-1009,sc2-1010,...,sc2-1046,sc2-1047,sc2-1048,sc2-1049,sc2-1050,sc2-1051,sc2-1052,sc2-1053,sc2-1054,sc2-1055
35_A,0.989160,0.989160,0.989160,0.989160,0.989160,0.989160,0.989160,1.000000,0.989160,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.989160,0.989160,1.00000
35_T,0.025968,0.025968,0.025968,0.025968,0.025968,0.025968,0.025968,0.000000,0.025968,0.000000,...,0.000000,0.033333,0.013514,0.000000,0.000000,0.000000,0.000000,0.025968,0.025968,0.00000
35_C,0.001626,0.001626,0.001626,0.001626,0.001626,0.001626,0.001626,0.000000,0.001626,0.000000,...,0.000000,0.016667,0.000000,0.000000,0.000000,0.000000,0.000000,0.001626,0.001626,0.00000
35_G,0.001690,0.001690,0.001690,0.001690,0.001690,0.001690,0.001690,0.000000,0.001690,0.000000,...,0.000000,0.016667,0.000000,0.000000,0.000000,0.000000,0.000000,0.001690,0.001690,0.00000
103_A,0.000000,0.000114,0.000114,0.000114,0.000114,0.000114,0.000114,0.000000,0.000000,0.000224,...,0.000000,0.000506,0.000000,0.000000,0.000000,0.000000,0.000209,0.000000,0.000000,0.00000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29767_G,0.000559,0.000000,0.000400,0.000400,0.000400,0.000400,0.000400,0.000923,0.000000,0.001152,...,0.000279,0.000258,0.000918,0.000491,0.000131,0.000709,0.000476,0.000000,0.000848,0.00026
29811_A,0.000000,0.000000,0.020169,0.020169,0.020169,0.020169,0.020169,0.000290,0.000000,0.000295,...,0.000000,0.000278,0.000000,0.000254,0.000000,0.000000,0.000330,0.000000,0.000000,0.00027
29811_T,1.000000,1.000000,0.980005,0.980005,0.980005,0.980005,0.980005,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000
29811_C,0.000557,0.000000,0.000231,0.000231,0.000231,0.000231,0.000231,0.000290,0.000000,0.000295,...,0.000000,0.000278,0.000279,0.000000,0.000000,0.000310,0.000000,0.000000,0.000000,0.00027
29811_G,0.000000,0.000000,0.000034,0.000034,0.000034,0.000034,0.000034,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000285,0.000000,0.000330,0.000000,0.000000,0.00000